from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent
RAW_DATA_DIR = ROOT_DIR / "data" / "raw"
PROCESSED_DATA_DIR = ROOT_DIR / "data" / "processed"
LOGS_DIR = ROOT_DIR / "logs"
MODELS_DIR = ROOT_DIR / "model"

SEQ_LEN = 128
BATCH_SIZE = 64
EMBEDDING_DIM = 128
HIDDEN_SIZE = 256
LEARNING_RATE = 1e-3
EPOCH_SIZE = 10
ENCODER_HIDDEN_SIZE = 512
DECODER_HIDDEN_SIZE = 512
ATTENTION_SIZE = 512
ENCODER_LAYERS = 2
MAX_SEQ_LENGTH = 256
